### ISSUE TITLE
I needed this...

### ISSUE THREAD

**Issue by everythingability** [wsvincent/djangox#24]
pip3 install django-allauth==0.27.0

**Comment by everythingability** [comment]
Nope. That didn't fix it...

I follow this and when I get to section 3 
python manage.py makemigrations users

I get..

Toms-MBP:djangox tomsmith$ pipenv shell
Launching subshell in virtual environment…
ln: /usr/local/bin/django-admin: File exists
bash-3.2$  . /Users/tomsmith/.local/share/virtualenvs/djangox-wqkjb2Qp/bin/activate
(djangox) bash-3.2$ python manage.py makemigrations users
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth'

**Comment by faulander** [comment]
It seems you got a problem with your virtual environment:
```
Launching subshell in virtual environment…
ln: /usr/local/bin/django-admin: File exists
bash-3.2$ . /Users/tomsmith/.local/share/virtualenvs/djangox-wqkjb2Qp/bin/activate
```
I would recreate the venv.

**Comment by everythingability** [comment]
Thanks...  that wasn't my venv though, mine in in env... so, never mind, but thanks anyway.
